version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - redis:/data

  web:
    build: .
    environment:
      - RAILS_ENV=development
      - DB_HOST="db"
      - DB_USER="postgres"
      - DB_PASSWORD="password"
      - DB_NAME="issue_viewer_development"
      - GITHUB_KEY=b4bba2e3e1df09019802
      - GITHUB_SECRET=370b7c577760cf70476865c2a1712afccac9c27d
    volumes:
      - web-sync:/app:nocopy
      - /app/node_modules/
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true

volumes:
  db:
  web:
  redis:
  web-sync:
    external: true
