version: 2
jobs:
  build:
    working_directory: ~/issue-viewer
    docker:
      - image: circleci/ruby:2.7.1-node
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: password
      - image: circleci/redis:alpine
      - image: circleci/postgres:9.6.2-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache
      - run:
          name: Install Bundler
          command: gem install bundler -v 2.1.4
      - run:
          name: Bundle
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache
          paths:
            - vendor/bundle
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run Tests
          command: bundle exec rspec --require spec_helper --color spec
