default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= ENV.fetch('DB_USER') { '' }%>
  password: <%= ENV.fetch('DB_PASSWORD') { '' } %>
  host: <%= ENV.fetch('DB_HOST') { '' } %>
  database: <%= ENV.fetch('DB_NAME') { '' } %>

test:
  <<: *default
  username: <%= ENV.fetch('DB_USER') { '' }%>
  host: <%= ENV.fetch('DB_HOST') %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' } %>
  database: issue_viewer_test

production:
  <<: *default
  database: issue_viewer_production
  username: issue_viewer
  password: <%= ENV['ISSUE_VIEWER_DATABASE_PASSWORD'] %>
